// <auto-generated />
namespace SCC_Marina.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatingDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatingDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202302201908402_updatingDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
